server:
  port: 8080
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    # 配置热部署
    cache: false
  #mysql配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tron
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.tron.pay.entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
tron:
  # 全节点请求的key 获取地址 https://www.trongrid.io/dashboard 每天可请求10w次
  apiKey: 10d92ad6-dc71-46f5-accd-5968932ba24f
  # 主网地址
  mainNet: https://api.trongrid.io
  # Shasta地址
  shastaNet: https://api.shasta.trongrid.io
  # nile地址
  nileNet: https://nile.trongrid.io
# 配置全局请求的url
tronPay:
  baseUrl: http://127.0.0.1:8080
  nileNet: https://nile.tronscan.org
  mainNet: https://tronscan.org
############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: tpaytoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true